---
version: '3.7'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: cis_user
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: testing-identity-vault
    ports:
      - 5432:5432
    networks:
      - default
  tester:
    build:
      context: ci/
      dockerfile: Dockerfile
    environment:
      AWS_DEFAULT_REGION: us-west-2
      AWS_DEFAULT_PROFILE: default
      AWS_ACCESS_KEY_ID: AKIAxxxxxxxxxxxx
      AWS_SECRET_ACCESS_KEY: AKIAxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - ./:/var/task
    networks:
      - default
    depends_on:
      - db